# Generated by Django 4.2.7 on 2023-11-06 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_heading", models.CharField(max_length=60)),
                (
                    "task_description",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deadline_date", models.DateTimeField(blank=True, null=True)),
                ("sub_tasks", models.ManyToManyField(blank=True, to="tasks.task")),
                (
                    "task_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_assigned",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["task_heading"],},
        ),
        migrations.AddField(
            model_name="user",
            name="owned_tasks",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to="tasks.task"
            ),
        ),
    ]
