# Generated by Django 4.2.6 on 2023-12-14 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
