# Generated by Django 4.2.7 on 2023-12-11 19:25

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment_commentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.validate_future_date]),
        ),
    ]
