# Generated by Django 4.2.6 on 2023-11-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_team_team_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_modified',
        ),
    ]
