# Generated by Django 4.2.6 on 2023-12-14 11:34

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.validate_future_date]),
        ),
    ]
