# Generated by Django 4.2.7 on 2023-11-25 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_team_creation_date_remove_team_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owned_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='team_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_assigned', to='tasks.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_owner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='teams_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='unique_identifier',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Unique Identifier must consist of # followed by at least three alphanumericals', regex='^#\\w{3,}$')]),
        ),
    ]
