# Generated by Django 4.2.6 on 2023-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_team"),
        ("tasks", "0002_team 2"),
        ("tasks", "0003_task_task_complete"),
    ]

    operations = []
