# Generated by Django 4.2.7 on 2023-11-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_team_owned_tasks_task_team_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gravatar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
